//! BIP-32 derivation paths for stealth scan and spend keys.
//!
//! This module is the **single source of truth** for the derivation paths
//! used by stealth meta-addresses. Anything that derives a scan or spend
//! key MUST go through [`scan_path`] / [`spend_path`] so a future ADR can
//! relocate the paths in exactly one place.
//!
//! TODO(#551): the path layout below is provisional. The
//! `m5-dd-paths` ADR (issue #551) is the authoritative document and may
//! choose a different `coin_type`, `purpose`, or hardening scheme. When
//! the ADR lands, update [`SCAN_BRANCH`], [`SPEND_BRANCH`], and the
//! constants in this module accordingly. Treat these defaults as
//! placeholders — DO NOT publish meta-addresses generated by this code
//! to mainnet users until the ADR is final.
//!
//! # Provisional layout
//!
//! Both keys share the BIP-44 prefix `m/44'/0'/account'/.../0'`, where
//! `account'` is hardened so distinct accounts produce independent
//! key trees:
//!
//! ```text
//!   scan : m/44'/0'/account'/0'/0'
//!   spend: m/44'/0'/account'/1'/0'
//! ```
//!
//! The branch index (`0'` vs `1'`) is the only differentiator between
//! the two keys at a given account. Both indices are hardened to keep
//! the scan-key disclosure (which a wallet may share with a watcher) from
//! revealing anything about the spend subtree.

use bitcoin::bip32::{ChildNumber, DerivationPath};

/// BIP-44 `purpose'` index. Hardened.
pub const PURPOSE: u32 = 44;

/// BIP-44 `coin_type'` index. Hardened.
///
/// TODO(#551): `0` (Bitcoin) is a placeholder. The ADR may register a
/// coin-type for Ark-on-Bitcoin or use a private range.
pub const COIN_TYPE: u32 = 0;

/// Hardened branch index reserved for the **scan** key subtree.
pub const SCAN_BRANCH: u32 = 0;

/// Hardened branch index reserved for the **spend** key subtree.
pub const SPEND_BRANCH: u32 = 1;

/// Hardened address-index used as the leaf in scan and spend paths.
///
/// We pin this at `0` for the meta-address itself. One-time keys
/// derived per-payment will use a different scheme (specified by the
/// ADR alongside the shared-secret tweak).
pub const ADDRESS_INDEX: u32 = 0;

/// Returns the BIP-32 derivation path for the scan key of `account`.
pub fn scan_path(account: u32) -> DerivationPath {
    branch_path(SCAN_BRANCH, account)
}

/// Returns the BIP-32 derivation path for the spend key of `account`.
pub fn spend_path(account: u32) -> DerivationPath {
    branch_path(SPEND_BRANCH, account)
}

fn branch_path(branch: u32, account: u32) -> DerivationPath {
    DerivationPath::from(vec![
        hardened(PURPOSE),
        hardened(COIN_TYPE),
        hardened(account),
        hardened(branch),
        hardened(ADDRESS_INDEX),
    ])
}

fn hardened(index: u32) -> ChildNumber {
    ChildNumber::from_hardened_idx(index)
        .expect("indices used in stealth derivation paths are within BIP-32 range")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scan_and_spend_paths_only_differ_on_branch_index() {
        let account = 7;
        let scan: Vec<ChildNumber> = scan_path(account).into_iter().copied().collect();
        let spend: Vec<ChildNumber> = spend_path(account).into_iter().copied().collect();

        assert_eq!(scan.len(), 5);
        assert_eq!(spend.len(), 5);
        assert_eq!(scan[0..3], spend[0..3]);
        assert_eq!(scan[4], spend[4]);
        assert_ne!(scan[3], spend[3]);
    }

    #[test]
    fn paths_are_fully_hardened() {
        let scan = scan_path(0);
        let spend = spend_path(0);
        for child in scan.into_iter().chain(&spend) {
            assert!(matches!(child, ChildNumber::Hardened { .. }));
        }
    }
}
